tinyMCE.addI18n('en.wp_gmaps2_dlg',{
	not_found: "not found!", 
	title:"Google Maps",
	general:"General",
	advanced:"Advanced Options", 
	map:"Map", 
	location: "Location", 
	coordinates: "Coordinates", 
	coordinates_latitude: "Latitude",
	coordinates_longitude: "Longitude",
	address: "Address", 
	defaultaddress: "city, country", 
	search: "Search", 
	map_size: "Map Size", 
	pixel: "Pixel", 
	width:"Width", 
	height:"Height", 
	map_options: "Map Options", 
	zoom_level: "Zoom Level",
	map_style: "Map Style", 
	map_style_normal: "Normal Map", 
	map_style_satellite: "Satellite Map", 
	map_style_hybrid: "Hybrid Map", 
	map_style_physical: "Physical Map", 
	map_controls: "Map Controls", 
	map_controls_simple: "Simple controls", 
	map_controls_3d: "3D Controls", 
	map_controls_none: "No controls", 
	invalid_coordinates: "Your coordinates are invalid!",
	error_ocorred: "Error",
	no_rows_selected: "You must selected the rows to be deleted!",
	map_separators: "Separators",
	map_separators_label: "Label",
	map_separators_content: "Content <small>(HTML is supported)</small>",
	map_separators_add: "Adds a separator",
	map_separators_remove: "Remove the selected separator(s)",
	map_icon: "Map Icon",
	map_icon_url: "Icon Image URL",
	map_icon_image_title: "The foreground image URL of the icon",
	map_icon_width_title: "The pixel width of the foreground image of the icon",
	map_icon_height_title: "The pixel height of the foreground image of the icon",
	icon_image_x: "X Anchor",
	icon_image_y: "Y Anchor",
	icon_image_x_title: "The X pixel coordinate relative to the left corner of the icon image at which this icon is anchored to the map",
	icon_image_y_title: "The Y pixel coordinate relative to the top corner of the icon image at which this icon is anchored to the map",
	map_icon_shadow_url: "Icon Shadow Image URL",
	map_icon_shadow_image_title: "The shadow image URL of the icon",
	map_icon_shadow_width_title: "The pixel width of the shadow image",
	map_icon_shadow_height_title: "The pixel height of the shadow image",
	map_icon_info_anchor: "Window anchor",
	icon_image_info_anchor_x_title: "The X pixel coordinate relative to the left corner of the icon image at which the info window is anchored to this icon",
	icon_image_info_anchor_y_title: "The Y pixel coordinate relative to the top corner of the icon image at which the info window is anchored to this icon"
});
