tinyMCE.addI18n('pt.wp_gmaps2_dlg',{
	not_found: "não encontrado", 
	title:"Mapas da Google",
	general:"Geral",
	advanced:"Opções Avançadas", 
	map:"Mapa", 
	location: "Localização", 
	coordinates: "Coordenadas", 
	coordinates_latitude: "Latitude",
	coordinates_longitude: "Longitude",
	address: "Endereço", 
	defaultaddress: "cidade, país", 
	search: "Procurar", 
	map_size: "Tamanho do Mapa", 
	pixel: "Pixel", 
	width:"Largura", 
	height:"Altura", 
	map_options: "Opções do Mapa", 
	zoom_level: "Nível de Zoom",
	map_style: "Estilo do Mapa", 
	map_style_normal: "Mapa Normal", 
	map_style_satellite: "Vista de Satélite", 
	map_style_hybrid: "Mapa Híbrido", 
	map_style_physical: "Mapa do Terreno", 
	map_controls: "Controles do Mapa", 
	map_controls_simple: "Simples", 
	map_controls_3d: "3D", 
	map_controls_none: "Sem controlos", 
	invalid_coordinates: "As coordenadas são inválidas!",
	error_ocorred: "Erro",
	no_rows_selected: "Deve seleccionar as linhas a serem eliminadas",
	map_separators: "Separadores",
	map_separators_label: "Etiqueta",
	map_separators_content: "Conteúdo <small>(é suportado HTML)</small>",
	map_separators_add: "Adiciona um separador",
	map_separators_remove: "Remove o(s) separador(es) seleccionado(s)",
	map_icon: "Ícone do Mapa",
	map_icon_url: "URL da Imagem do Ícone",
	map_icon_image_title: "Endereço da imagem de primeiro plano a utilizar como ícone",
	map_icon_width_title: "A largura em pixeis da imagem a utilizar como ícone",
	map_icon_height_title: "A altura em pixeis da imagem a utilizar como ícone",
	icon_image_x: "Âncora do X",
	icon_image_y: "Âncora do Y",
	icon_image_x_title: "A coordenada X em pixeis relativa ao canto esquerdo da imagem ao qual este ícone estará âncorado no mapa",
	icon_image_y_title: "A coordenada Y em pixeis relativa ao topo da imagem ao qual este ícone estará âncorado no mapa",
	map_icon_shadow_url: "URL da Imagem de Sombra",
	map_icon_shadow_image_title: "Endereço da imagem a utilizar como sombra do ícone",
	map_icon_shadow_width_title: "A largura em pixeis da imagem a utilizar como sombra do ícone",
	map_icon_shadow_height_title: "A altura em pixeis da imagem a utilizar como sombra do ícone",
	map_icon_info_anchor: "Âncora da Janela",
	icon_image_info_anchor_x_title: "A coordenada X em pixeis relativa ao canto esquerdo da imagem à qual a janela de informações é âncorada a este ícone",
	icon_image_info_anchor_y_title: "A coordenada Y em pixeis relativa ao topo da imagem à qual a janela de informações é âncorada a este ícone"
});
